# APP
appMount: .appMount-3lHmkl
platformWin: .platform-win
platformOSX: .platform-osx
platformLinux: .platform-linux
platformWeb: .platform-web
colorblindMode: .colorblind-mode
themeDark: .theme-dark
themeLight: .theme-light
app: .app-19_DXt
shakeable: .app-2rEoOp
layers: .layers-3iHuyZ
layer: .layer-3QrUeG
layerAnimating: .animating-rRxada
layerStopAnimations: .stop-animations
containerMain: .container-2lgZY8
base: .base-3dtUhz
backdrop: .backdrop-1wrmKB